batch_size: 256
# batch_size: 1024
hid_dim: 256
lr: 0.003
#lr: 3
wd: !!float 1e-4
n_layers: 2
dropout: [0.2, 0.1]
device: "cuda:0"
early_stopping: 100
n_fold: 5
seed: 2023
max_epochs: 300
gated: True
test_size: 0.2



